### ISSUE TITLE
Please remove dependencies we don't need

### ISSUE THREAD

**Issue by somaritane** [iflix-letsplay/wdio-datadog-reporter#1]
Please remove dependencies from package.json that we don't need (ava, istanbul etc)

**Comment by vadiminc** [comment]
we need it. istanbul we use for conver. ava for tests, I didn't have time to write the test yet. but these dependencies we need for dev

**Comment by SomeoneWeird** [comment]
You should switch to `nyc` instead of `istanbul` for coverage :)

**Comment by somaritane** [comment]
When we use any of these, then we bring in required dependencies, until then - it makes no sense to bring them in.

**Comment by somaritane** [comment]
On other topic, 'istanbul' plugins for mocha/ava vs 'nyc' CLI, 'ava' vs 'mocha', i don't care as long as a tool does it's job but is consistent across the engineering org, at least in web/back-end, otherwise we get zoo of tools.
